---
title: "R Notebook"
output: html_notebook
---

.

```{r}
source("qPCRfunctions.R")
library(ggplot2)
library(readxl)
library(shiny)
```

```{r}
efficancies <- list(
  RpS6 =  1.99, #empiric
  RpS18 = 1.93, #empiric
  FABP =  1.91, #empiric
  CHS1 =  2.00, #empiric
  Exp =   1.95 #empiric
)
```

```{r}
RefG <-       "RpS18" # enter your reference gene
genes <- list("FABP") # enter all your genes w/o reference gene
loadPath <-   "C:/Users/beckm/OneDrive/Desktop/micPCR/FABP15275/FABP15275_L1-P0.xlsx"
storePath <-  "C:/Users/beckm/OneDrive/Desktop/micPCR"
```

```{r}

#load data
DataTable <- read_excel(loadPath)

#prepare your data
ValueTable <- dataPrep(DataTable, RefG, genes)

#normalize Ct values with Primerefficancies against reference gene and calculate deltaCt
for (gene_name in genes) {
  assign(paste0(gene_name, "_plot"), plotPrep(efficancies, RefG, gene_name, get(gene_name)))
  
}
```

```{r fig.height=10, fig.width=10}
selectInput("dropdown", "Choose an Option:", choices = c("Option A", "Option B", "Option C"))
```

```{r}
#plot data
for (gene_name in genes) {
  ggplot(data = get(paste0(gene_name, "_plot")), aes(x = Sample, y = normCt)) + geom_boxplot()
  #ggsave(paste0(gene_name, "_normalized.tiff"), path = storePath)
  #ggsave(paste0(gene_name, "_normalized.svg"), path = storePath)
  
  #ggplot(data = get(gene_name), aes(x = Sample, y = deltaCt)) + geom_boxplot()
}

```
